### ISSUE TITLE
Does not run with Python 3.9

### ISSUE THREAD

**Issue by JanaTeepunkt** [PopovicMilica/causal_nets#2]
Hey,

I just wanted you to know that the package does not run with Python 3.9, because it can not install the required ("older") numpy version. I succesfully installed it with Pyhton 3.8.7.

Thanks a lot for the package, it helps me writing my masterthesis! :)

**Comment by Hakan-indp** [comment]
what is your choose's OS for use that?

**Comment by JanaTeepunkt** [comment]
Windows 10

**Comment by PopovicMilica** [comment]
Hey Jana,

I'm glad that you are finding the package useful. :) The problem with supporting Python 3.9 was tensorflow. Although Python 3.9 was released in October last year, TensorFlow only introduced support for it in version 2.5.0, a stable version of which was only released recently (https://github.com/tensorflow/tensorflow/releases). Since the latest tensorflow version 2.5.0-rc3 is quite stable, I tweaked requirements.txt to allow this version of tensorflow to be installed. So, if you go through the installation again, the problem should be solved. Let me know if it works now for you. Good luck with your master thesis!
