### ISSUE TITLE
Unable to run causal_nets

### ISSUE THREAD

**Issue by klaushajdaraj** [PopovicMilica/causal_nets#6]
Hi @PopovicMilica ,

I am currently trying to run (and debug) the `causal_net_estimate` function in Python.
I receive the following error message:

`ValueError: Argument(s) not recognized: {'lr': 0.0009}`
I expect this error to be related to `learning_rate` argument, which is denoted as `lr` in this case.

**Environment**:
- Operating system: Windows 10
- Python Version: 3.12.2

**Description**:

I attempted to run the short code example provided in the README section of the causal_nets GitHub repository.

**Steps to Reproduce**:
1. Clone the causal_nets repository from GitHub.
2. Navigate to the examples directory.
3. Run the provided code example.

Any insights or suggestions to resolve this issue would be greatly appreciated.
I am currently trying to implement this method for my Master Thesis, so I would highly appreciate any advice on how to overcome this issue and manage to run the `causal_nets`.

Thank you in advance,
Best,
Klaus

**Comment by NormProgr** [comment]
Hi @klaushajdaraj,

the issue is most likely due to an outdated version of tensorflow being used. I can't fully pin down the exact issue but one of the following steps helped me to overcome the issue:

```
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from scipy.stats import norm
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION="python"  # add this 
from causal_nets import causal_net_estimate
import tensorflow as tf   # add this
```
and downgrade these packages.
```
pip install tensoflow==2.10.0
pip install protobuf==3.11.3
```
Propably other versions of tensorflow<=2.3 will work and also other versions of protubuf but that was the exact one working for me. Not the best solution but maybe better than none :)

Tested on Windows 11; Python Version 3.9.19.

Good luck with the Master Thesis.

Best,
Norm

**Comment by klaushajdaraj** [comment]
Hi @NormProgr ,

I just tested your suggested solution, and... it worked!!!
Thanks a lot for your quick and effective assistance!:) 

**Tested on**:
- Windows 11
- Python 3.9.13
- tensoflow 2.10.0
- protobuf 3.11.3

Many thanks again!
Best,
Klaus
